/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codingdie_util_media_MediaUtil */

#ifndef _Included_com_codingdie_util_media_MediaUtil
#define _Included_com_codingdie_util_media_MediaUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codingdie_util_media_MediaUtil
 * Method:    getVideoInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codingdie_util_media_MediaUtil_getVideoInfo
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
